apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: oci-vault
spec:
  provider:
    oracle:
      vault: ocid1.vault.oc1.ap-osaka-1.fztg254daae4o.abvwsljrapad4zplys7zrkmc4v6evdeilei7g2ukfxsf2pknnwqltkdulscq
      region: ap-osaka-1
      principalType: UserPrincipal
      auth:
        tenancy: ocid1.tenancy.oc1..aaaaaaaakd5esaiyaq6rlully7ieql4fnmnczl5fvfkq6vjmpbwj7ubv5pta
        user: ocid1.user.oc1..aaaaaaaas3amcpqxn66egalneubw3a4iuiksgrhn6d5usmehmmyzxfzv5rqq
        secretRef:
          privatekey:
            name: oracle-secret
            key: privateKey
            namespace: eso
          fingerprint:
            name: oracle-secret
            key: fingerprint
            namespace: eso

---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: oracle-secret
#   namespace: eso
#   labels:
#     type: oracle
# type: Opaque
# stringData:
#   privateKey: |-
#     -----BEGIN PRIVATE KEY-----
#     -----END PRIVATE KEY-----
#   
#   fingerprint: finger