defaultNamespace: eso
helm:
  chart: external-secrets
  repo: https://charts.external-secrets.io
  version: 0.12.1
  values:
    # Additional configuration can be added here based on requirements
    # For example:
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi