kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: infrastructure
  namespace: cattle-fleet-system

spec:
  repo: https://github.com/solufit/fleet
  branch: main
  paths:
  - infrastructure
  targets:
  - clusterSelector: {}
  # Selector ignored
  - clusterSelector: null
