apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-external-secret-eso
  namespace: cft
spec:
  refreshInterval: 0.03m
  secretStoreRef:
    kind: ClusterSecretStore
    name: oci-vault
  target:
    name: cloudflare-api
    creationPolicy: Owner
  data:
    - secretKey: cloudflare-account-id
      remoteRef:
        key: manager-cft-account-id

    - secretKey: cloudflare-tunnel-name
      remoteRef:
        key: manager-cft-tunnel-name
    - secretKey: api-token
      remoteRef:
        key: manager-cft-api-token